apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: my-namespace
  labels:
    app: nginx-demo
spec:
  nodeSelector:
    kubernetes.io/os: windows    # Specify Windows nodes
  containers:
  - name: nginx
    image: hello-world-nginx:v1
    imagePullPolicy: Always
    ports:
    - containerPort: 80
